feed/urls.py
from django.urls import path

from feed import views
app_name = "feed"

urlpatterns = [
    path('', views.PostList.as_view(), name='post-list'),
    path('upload/', views.upload_post, name='upload-post'),
    path('<int:pk>/', views.PostDetail.as_view(), name='post-detail'),
    path('list-api/', views.PostListView.as_view(), name='post-list-api'),
]  

peto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from rest_framework.urlpatterns import format_suffix_patterns
from django_private_chat import urls as django_private_chat_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('pets.urls')),
    path('user/', include('user.urls')),
    path('', include('django_private_chat.urls')),
    path('feed/', include('feed.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here

] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html'])

pets/urls.py
from django.urls import path

from pets import views
app_name = "pets"
urlpatterns = [
    path('pets/', views.PetList.as_view(), name='pet-list'),
    path('pets/<int:pk>/', views.PetDetails.as_view(), name='pet-details'),
    path('pets/upload', views.PetCreateView, name='image_upload'),
    path('pets/update/<int:pk>', views.PetUpdateView.as_view(),
         name='pet_update'),
    path('pets/delete/<int:pk>', views.PetDeleteView.as_view(),
         name='pet_delete'),
    path('pets/adopted-pets/<int:pk>', views.set_pet_adopted,
         name='pet_adopted'),
    path('pets/adopted-pets/', views.MyAdoptedPetsView.as_view(),
         name='adopted-pets'),
    
    path('pets/search/', views.search, name='search'),
    path('pets/maps/<int:pk>/', views.OpenMaps.as_view(), name = 'map'),
]

map/models.py
from django.db import models

# Create your models here.

pets/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from pets.search import PetIndex


class Pet(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="publisher",
        on_delete=models.CASCADE)
    pet_name = models.CharField(max_length=30)
    breed = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    vaccinated = models.BooleanField(default=True)
    sterlized = models.BooleanField(default=True)
    age = models.IntegerField()
    general_behaviour = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    address = models.CharField(max_length=1000)
    is_adopted = models.BooleanField(default=False)

    def indexing(self):
        print(" inside model indexing")
        peto = PetIndex(
            meta={'id': self.id},
            pet_name=self.pet_name,
            breed=self.breed,
            id=self.id
        )
        peto.save()
        return peto.to_dict(include_meta=True)


class Image(models.Model):
    pet_id = models.ForeignKey(
        Pet, on_delete=models.CASCADE, related_name='image')
    image = models.ImageField(upload_to='images/')

pets/forms.py
from django import forms
from django.forms import ModelForm

# from markdownx.fields import MarkdownxFormField

from pets.models import Pet, Image

class PetForm(ModelForm):

    class Meta:
        model = Pet
        fields = ('pet_name',
                  'breed',
                  'gender',
                  'vaccinated',
                  'age', 
                  'sterlized',
                  'gender',
                  'general_behaviour',
                  'description',
                  'address')

class ImageForm(ModelForm):
    
    class Meta:
        model = Image
        fields = ('image',)

map/views.py
from django.shortcuts import render

# Create your views here.

pets/views.py
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from django.shortcuts import render
from user.models import Profile
from django.shortcuts import redirect
from rest_framework import generics
from django.template.context_processors import csrf
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import permissions
from django.forms import modelformset_factory
from django.http import HttpRequest
from django.db.models import Q

from pets.models import Pet, Image
from pets.search import elastic_search
from pets.serializers import GetAllImageSerializer, PetSerializer
from pets.forms import PetForm, ImageForm
from pets.permissions import IsUserOrReadOnly
from math import sin, cos, sqrt, atan2, radians
import random
# dummy lat and long values for testing
list_of_locations = [[16.166700, 74.833298], [26.850000, 80.949997],
                     [28.610001, 77.230003], [19.076090, 72.877426],
                     [14.167040, 75.040298], [26.540457, 88.719391], ]

# from pets.models import Pet, Image


def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0
    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    distance = R * c
    return distance


# generates a list of pets
class PetList(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'pets/pet_list.html'

    def get(self, request, format=None):

        id = request.user.id
        person = Profile.objects.get(id=id)
        lat1 = person.latitude
        lon1 = person.longitude

        pets = Pet.objects.filter(is_adopted=False)
        for pet in pets:
            lat2 = pet.latitude
            lon2 = pet.longitude
            distance = calculate_distance(lat1, lon1, lat2, lon2)
            pet.first_image = pet.image.first()
            pet.distance = round(distance)
        return Response({'pets': pets})


# gets details of the selected pet
class PetDetails(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'pets/pet_details.html'

    def get(self, request, pk, format=None):
        id = request.user.id
        person = Profile.objects.get(id=id)
        lat1 = person.latitude
        lon1 = person.longitude
        queryset = Pet.objects.get(id=self.kwargs['pk'])
        queryset_image = Image.objects.filter(pet_id_id=self.kwargs['pk'])
        number_image = len(queryset_image)
        lat2 = queryset.latitude
        lon2 = queryset.longitude
        distance = calculate_distance(lat1, lon1, lat2, lon2)
        queryset.distance = round(distance)
        return Response({'pet': queryset, 'images': queryset_image,
                         'n': number_image})


# class PetListView(generics.ListAPIView):
#     queryset = Pet.objects.all()
#     serializer_class = PetSerializer

#     def perform_create(self, serializer):
#         serializer.save(user=self.request.user)

# class PetDetailView(generics.RetrieveAPIView):
#     queryset = Pet.objects.all()
#     serializer_class = PetSerializer


class PetUpdateView(generics.UpdateAPIView):
    queryset = Pet.objects.all()
    serializer_class = PetSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsUserOrReadOnly)


class PetDeleteView(generics.DestroyAPIView):
    queryset = Pet.objects.all()
    serializer_class = PetSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsUserOrReadOnly)

# function to get the locaiton of the user while uploading the pets


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


# class based view to to upload a pet to into the database
def PetCreateView(request):
    template_name = 'pets/pet_upload.html'
    # change extra depending upon how many images you want
    image_form_set = modelformset_factory(Image, form=ImageForm, extra=2)
    if request.method == 'POST':
        pet_form = PetForm(request.POST)
        image_form = image_form_set(
            request.POST, request.FILES, queryset=Image.objects.none())
        if pet_form.is_valid() and image_form.is_valid():
            pet = pet_form.save(commit=False)
            pet.user = request.user
            # while deploying the project to get ip address
            client_ip = get_client_ip(request)
            pet.longitude = random.choice(list_of_locations)[1]
            pet.latitude = random.choice(list_of_locations)[0]
            pet.save()

            for single_form in image_form.cleaned_data:
                single_image = single_form['image']
                image_object = Image(image=single_image, pet_id=pet)
                image_object.save()

        return redirect("pets:pet-list")

    else:
        pet_form = PetForm()
        iformset = image_form_set(queryset=Image.objects.none())

    args = {}
    args.update(csrf(request))
    args['pet_form'] = pet_form
    args['image_form_set'] = iformset
    return render(request, template_name, args)


def set_pet_adopted(request, *args, **kwargs):
    pet = Pet.objects.get(pk=kwargs['pk'])
    if pet.user == request.user:
        pet.is_adopted = True
        pet.save()
    return redirect("pets:adopted-pets")
    # retun to the same page


class MyAdoptedPetsView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'pets/adopted_pets.html'

    def get(self, request, format=None):
        pets = Pet.objects.filter(user=request.user)
        for pet in pets:
            pet.first_image = pet.image.first()

        return Response({'pets': pets})


# elasticsearch for searching pets through breed
def search(request):

    template_name = 'pets/pet_list.html'

    query = request.GET.get('q', '')
    # code for normal search
    # pets = Pet.objects.filter(Q(pet_name__icontains=query) | 
    #                           Q(breed__icontains=query))
    pets = Pet.objects.filter(breed__in=elastic_search(query))
    for pet in pets:
        pet.first_image = pet.image.first()
    return render(
        request, template_name, {'pets': pets})


class OpenMaps(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'pets/maps.html'
    def get(self, request, *args, **kwargs):
        pet = Pet.objects.get(pk = kwargs['pk'])
        name = pet.pet_name
        latitude=float(pet.latitude)
        longitude=float(pet.longitude)
        return Response({'latitude': latitude, 'longitude':longitude, 'name': name})

templates/pets/adopted_pets.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    {% for pet in pets %}
    <div class="gallery">
        <a target="_blank" href="{% url 'pets:pet-details' pet.id %}">
            <img src="{{ pet.first_image.image.url }}" alt="Cinque Terre">
        </a>
        <div class="desc">
            <div>
                <b>{{ pet.pet_name }}</b>
            </div>
            <div>
                {{ pet.breed }}
            </div>
            <div>
               {{ pet.gender }}
            </div>
            <div>
                {% if pet.is_adopted %}
                <div style="color: green"><strong>Adopted</strong></div>
                {% else %}
                <a href="{% url 'pets:pet_adopted' pet.pk%}" class="btn btn-primary adopt" style="color:white" role="button">Given away</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    
</div>

{% endblock content %}

templates/pets/maps.html
<!DOCTYPE html>
<html>
 <head>
   <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
   <meta charset="utf-8">
   <title>Peto Maps</title>

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

   <style>
     /* Always set the map height explicitly to define the size of the div
      * element that contains the map. */
     #map {
       height: 100%;
     }
     /* Optional: Makes the sample page fill the window. */
     html, body {
       height: 100%;
       margin: 0;
       padding: 0;
     }
   </style>
   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCF0TI828siwFP5ATOyuhWfu8btlk2KgWI"></script>
   <script>
     // In the following example, markers appear when the user clicks on the map.
     // Each marker is labeled with a single alphabetical character.
     var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
     var labelIndex = 0;

     function initialize() {
       lati = parseFloat($('#latitude').text())
       longi = parseFloat($('#longitude').text())
       var  loc = { lat: lati, lng: longi };
       var map = new google.maps.Map(document.getElementById('map'), {
         zoom: 12,
         center: loc
       });

       // This event listener calls addMarker() when the map is clicked.
       // google.maps.event.addListener(map, 'click', function(event) {
       //   addMarker(event.latLng, map);
       // });

       // Add a marker at the center of the map.
       addMarker(loc, map);
     }

     // Adds a marker to the map.
     function addMarker(location, map) {
       // Add the marker at the clicked location, and add the next-available label
       // from the array of alphabetical characters.
       var marker = new google.maps.Marker({
         position: location,
         label: $('#name').text(),
         map: map
       });
     }

     google.maps.event.addDomListener(window, 'load', initialize);
   </script>
 </head>
 <body>
   <div id="map"></div>
   <p id = 'latitude'>{{ latitude }}</p>
   <p id = 'longitude'>{{ longitude }}</p>
   <p id = 'name'>{{ name }}</p>
 </body>
</html>

templates/pets/pet_details.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
{% block modal%}
<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var num = "{{ n }}";
  var slides = document.getElementsByClassName("pet_image");
  if (n > num) {slideIndex = 1}    
  if (n < 1) {slideIndex = num}
  for (i = 0; i < num; i++) {
      slides[i].style.display = "none";  
  }
  slides[slideIndex-1].style.display = "block";  
}
    </script>
{% endblock modal %}
{% endblock head %}
{% block content %}


    <div class="detail-container">
      <div class="pet-name"><b>{{ pet.pet_name }}</b></div>
      <div class="characterstics">{{ pet.age }} yr old {{ pet.breed }}</div>
      <div class="characterstics">Lives in {{ pet.address }}</div>
      <div class="characterstics"> {{ pet.distance }} Km far </div>

      <div id="slider-container">
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
          {% for image in images %}
              <div class="pet_image fader"><img id="pet_images" src='{{ image.image.url }}' width="500px" height="300px"></div>
          {% endfor %}
          
          <a class="next" onclick="plusSlides(1)">&#10095;</a>
      </div>
      <div class="other-details">
          <div class="labels">Behaviour</div>
          <div class="characterstics2">{{ pet.general_behaviour }}</div>
          <div class="labels">Description</div>
          <div class="characterstics2">{{ pet.description }}</div>
          <div class="labels">Gender</div>
          <div class="characterstics2">{{ pet.gender }}</div>
          <div class="labels">Vaccinated</div>
          <div class="characterstics2">{{ pet.vaccinated }}</div>
          <div class="labels">Sterlized</div>
          <div class="characterstics2">{{ pet.sterlized }}</div>
          <a href="http://localhost:8000/dialogs/{{pet.user}}" class="btn btn-primary" id="chat-button" style="color:white" role="button">Chat</a><br>
          <a href= "http://localhost:8000/home/pets/maps/{{pet.id}}" class="btn btn-primary" id="chat-button" style="color:white" role="button">locate pet</a>

      </div>
    </div>
    <br><br>
    {% endblock content %}

templates/pets/pet_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<script type="text/javascript">
function emptyInput() {
        document.getElementById('search-id').value = '';
}
window.onload = emptyInput;
</script>
{% endblock head %}


{% block content %}
<div class="container">
    {% for pet in pets %}
    <div class="gallery">
        <a href="{% url 'pets:pet-details' pet.id %}">
            <img src="{{ pet.first_image.image.url }}" alt="Pet image">
        </a>
        <div class="desc">
            <div>
                <b>{{ pet.pet_name }}</b>
            </div>
            <div>
                {{ pet.breed }}
            </div>
            <div>
               {{ pet.gender }}
            </div>
            <div>
                    <strong>Distance: </strong>{{ pet.distance }} Km<br>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/pets/pet_upload.html
<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8"> 
    <title>peto</title> 
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <style>
        body{
            background-image:url(https://s7d2.scene7.com/is/image/PetSmart/GN0314_LG_MENU-DogAndCat-20160818?$GN3014$);
            display:flex;
            background-repeat: no-repeat;
            justify-content: flex-end;
            font-family: 'Montserrat', sans-serif;
        }
        .upload-content {
            width: 50%; 
            height: 50%;
            background: white;
            opacity:0.9;
            background-size: cover;
            color: black; /* Grey text */
            z-index:2 ;
            min-width: 200px;
            max-width: 400px;
            padding:5% 10% 5% 10%;
        }
    </style>
</head> 
<body>
    <div class="upload-content">
        <h2>Add Pet</h2>
        <form method = "post" enctype="multipart/form-data"> 
            {% csrf_token %} 
            <!-- {{ pet_form.as_p }}  -->
            {% for field in pet_form %}
                <p>
                    <strong>{{ field.label_tag }}</strong><br>
                    {{ field }}
                    {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            {{ image_form_set.management_form }}
            {% for form in image_form_set %}
                <!-- {{ form }} -->
                <p>
                        <strong>{{ form.label_tag }}</strong><br>
                        {{ form }}
                        {% if form.help_text %}
                        <small style="color: grey">{{ form.help_text }}</small>
                        {% endif %}
                        {% for error in form.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %}
                </p>
            {% endfor %}
            <button type="submit">Upload</button> 
        </form>
    </div>
    
</body> 

</html> 