feed/urls.py
from django.urls import path

from feed import views
app_name = "feed"

urlpatterns = [
    path('', views.PostList.as_view(), name='post-list'),
    path('upload/', views.upload_post, name='upload-post'),
    path('<int:pk>/', views.PostDetail.as_view(), name='post-detail'),
    path('list-api/', views.PostListView.as_view(), name='post-list-api'),
]  

peto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from rest_framework.urlpatterns import format_suffix_patterns
from django_private_chat import urls as django_private_chat_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('pets.urls')),
    path('user/', include('user.urls')),
    path('', include('django_private_chat.urls')),
    path('feed/', include('feed.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here

] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html'])

pets/urls.py
from django.urls import path

from pets import views
app_name = "pets"
urlpatterns = [
    path('pets/', views.PetList.as_view(), name='pet-list'),
    path('pets/<int:pk>/', views.PetDetails.as_view(), name='pet-details'),
    path('pets/upload', views.PetCreateView, name='image_upload'),
    path('pets/update/<int:pk>', views.PetUpdateView.as_view(),
         name='pet_update'),
    path('pets/delete/<int:pk>', views.PetDeleteView.as_view(),
         name='pet_delete'),
    path('pets/adopted-pets/<int:pk>', views.set_pet_adopted,
         name='pet_adopted'),
    path('pets/adopted-pets/', views.MyAdoptedPetsView.as_view(),
         name='adopted-pets'),
    
    path('pets/search/', views.search, name='search'),
    path('pets/maps/<int:pk>/', views.OpenMaps.as_view(), name = 'map'),
]

user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'
urlpatterns = [
    url(r'signup/$', views.signup, name='signup'),
    url(r'login/$', views.loginView, name='login'),
    url(r'home/$', views.homeView, name='home'),
    url(r'logout/$', views.logout_view, name='logout_view'),
    url(r'profile/$', views.ProfileView.as_view(), name='profile')
]

templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/petoicon4.png' %}">
    <title>{% block title %}Peto!{% endblock title %}</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    {% block css %}
    {{ block.super }}
    <link href="{% static 'django_private_chat/css/django_private_chat.css' %}" rel="stylesheet" type="text/css"
        media="all">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'css/peto.css'%}">
    {% endblock css %}
    {% block head %}{% endblock head %}
</head>

<body>
    {% block body %}
    <header>
        <div class="menu">
            <div class="logo">
                <img src="{% static 'img/petoicon4.png' %}" width="40%" height="40%">
                <h1>Peto!</h1>
            </div>
            <div class="nav-list">
                <div class="search-div">
                    <form method="GET" action="{% url 'pets:search' %}">
                        <input id="search-id" class="search-box" name="q" value="{{request.GET.q}}"
                            placeholder="search..">
                        <button type="submit" class="btn-success"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <a href="{% url 'pets:pet-list' %}" class="nav_li">Home</a>
                <a href="{% url 'pets:image_upload' %}" class="nav_li">Add pet</a>
                <a href="{% url 'pets:adopted-pets' %}" class="nav_li">Adopted pets</a>
                <a href="{% url 'feed:post-list' %}" class="nav_li">Feed</a>
                <a href="{% url 'user:logout_view' %}" class="nav_li">Logout</a>
                
                <a href="{% url 'user:profile' %}" class="nav_li"><i class="fa fa-user" aria-hidden="true"></i></a>&nbsp
                {% block username %}
                <p class="nav_li"> Welcome, {{ request.user.username }}</p>
                {% endblock %}
            </div>
            <div>
                <i class="hamburger fa fa-bars"></i>
            </div>

        </div>
    </header>
    {% block content %}
    <p></p>
    {% endblock content %}

    {% block modal %}{% endblock modal %}
    {% endblock body %}
    <div id="demo"></div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

<script>

    $(".hamburger").click(function () {
        $(".mobile-nav").toggle()

    })




</script>
{% block extra_js %}{% endblock extra_js %}
{% block script %}



{% endblock %}


<div class="footer-div">&copy;2019 TeamPeto!</div>


</html>